name: Build Legacy Update NT

on:
  push:
    branches: []
  pull_request:
    branches: []
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up
      run: |
        sudo apt-get update -q
        sudo apt-get install -qy curl make mingw-w64-x86-64-dev nsis p7zip-full upx-ucl unzip

    - name: Install MinGW toolchain
      run: |
        curl -fsSL https://linuxfromscratch.org/~renodr/gcc-15.1-binutils-2.45-mingw-v13.0.0-i686.tar.xz -o /tmp/mingw32.tar.xz
        curl -fsSL https://linuxfromscratch.org/~renodr/gcc-15.1-binutils-2.45-mingw-v13.0.0-x86_64.tar.xz -o /tmp/mingw64.tar.xz
        sudo tar -xf /tmp/mingw32.tar.xz -C /opt
        sudo tar -xf /tmp/mingw64.tar.xz -C /opt
        rm /tmp/mingw{32,64}.tar.xz

    - name: Install custom NSIS package
      run: |
        curl -fsSL https://linuxfromscratch.org/~renodr/nsis-3.11-ubuntu24-v2.tar.xz -o /tmp/nsis-3.11.tar.xz
        sudo tar -xf /tmp/nsis-3.11.tar.xz -C /opt
        rm /tmp/nsis-3.11.tar.xz

    - name: Download patches
      run: |
        ./build/get-nt4-patches.sh

    - name: Build
      id: build
      run: |
        export PATH=/opt/gcc-15.1-binutils-2.45-mingw-v13.0.0-i686/bin:$PATH
        export PATH=/opt/gcc-15.1-binutils-2.45-mingw-v13.0.0-x86_64/bin:$PATH
        export PATH=/opt/nsis-3.11/bin:$PATH
        make -j$(nproc) CI=1 DEBUG=0 nt4

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          setup/LegacyUpdateNT-*.exe
